[package]
name = "usbip"
version = "0.2.1"
authors = ["Jiajie Chen <c@jia.je>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/jiegec/usbip"
description = "A library to run USB/IP server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3.2", features = ["rt", "net", "stream", "io-util"] }
log = "0.4.11"
futures = "0.3.7"
num-traits = "0.2.14"
num-derive = "0.3.3"
rusb = "0.6.5"

[dev-dependencies]
tokio = { version = "0.3.2", features = ["full"] }
env_logger = "0.8.1"
